# Generated by Django 4.0.6 on 2022-08-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='loved',
        ),
    ]
