# Generated by Django 4.0.6 on 2022-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('brand', ''), _negated=True)), fields=('name', 'brand'), name='unique_product_and_brand'),
        ),
    ]
