# Generated by Django 4.0.6 on 2022-08-13 11:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('desired_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_changes', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True), size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwatchlistitem', to=settings.AUTH_USER_MODEL)),
                ('watchlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistitem', to='products.product')),
            ],
            options={
                'ordering': ('watchlist_item', '-created_on'),
            },
        ),
    ]
